version: '2.21'

services:
  gui_detector:
    build:
      context: ./GUI_det/
      dockerfile: Dockerfile
    container_name: gui_detector
    hostname: gui_detector
    ports:
      - "8873:8873"
    networks:
      - cursach-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
networks:
  cursach-network:
    driver: bridge
    external: true